### ISSUE TITLE
Проект закрыт?

### ISSUE THREAD

**Issue by Tom910** [immosmart/SmartboxV2#1]
Будет дальнейшее развитие или v1 версию можно считать финальной?

**Comment by DChinin** [comment]
V2 точно не получит продолжения. На развитие Smartbox не хватает времени. Сейчас изменились взгляды на разработку приложений под STB и TV.  Новый фреймворк находится в стадии разработки в закрытом виде,  в open-source будет перенесен частично в мае.  Можете отписаться мне на почту, проконсультирую по существующим решениям
